### ISSUE TITLE
Switch from materialize to bootstrap (MIKE)

### ISSUE THREAD

**Issue by jwilson99** [tcg-organizer/tcg-deck-builder#10]
Fix it!!!!!

**Comment by Klejman** [comment]
might have missed it but the currently says Materialize is the css framework. If we are using bootstrap do you mind pushing the revised main.handlebars file or don't mind tweaking it myself so long as I have your approval (don't want to step on anyone's toes here).

**Comment by jwilson99** [comment]
Hi, Katie.

I put Mike's name on it, because he's the only one who has pushed
materialize code. We decided to switch over to bootstrap, so he was going
to update his code.

Julie


On Nov 22, 2017 11:46 AM, "Katie Mary Lejman" <notifications@github.com>
wrote:

might have missed it but the currently says Materialize is the css
framework. If we are using bootstrap do you mind pushing the revised
main.handlebars file or don't mind tweaking it myself so long as I have
your approval (don't want to step on anyone's toes here).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tcg-organizer/tcg-deck-builder/issues/10#issuecomment-346408115>,
or mute the thread

**Comment by Rogwzrd** [comment]
DONE
